### ISSUE TITLE
UML Use Case Diagram

### ISSUE THREAD

**Issue by robertofiguz** [CSDET10/GP2#11]
- [x] the main actors - those human/external systems who may be using the system

- [x] possible use cases

- [x] at least, ONE use case connected to others by \<\<include\>\>

- [x] at least, ONE use case connected to others by \<\<extend\>\>

**Comment by jcohen96** [comment]
[UML_v1.zip](https://github.com/CSDET10/GP2/files/3945823/UML_v1.zip)

@robertofiguz

**Comment by robertofiguz** [comment]
@jcohen96 @mgrosmaninho @Matthew-Chamberlain @iTiagoL

Hey! please confirm everything in the UML diagram is correct and consistent or if there is something missing. (if you find everything to be all good react with a 👍 else just comment it please )
[UML-PNG file inside ZIP](https://github.com/CSDET10/GP2/tree/master/UML)

**Comment by mgrosmaninho** [comment]
> @jcohen96 @mgrosmaninho @Matthew-Chamberlain @iTiagoL
> 
> Hey! please confirm everything in the UML diagram is correct and consistent or if there is something missing. (if you find everything to be all good react with a 👍 else just comment it please )
> [UML-PNG file inside ZIP](https://github.com/CSDET10/GP2/tree/master/UML)

Looks good. Thanks!!!

**Comment by jcohen96** [comment]
I think is fine
