### ISSUE TITLE
UCDescription1

### ISSUE THREAD

**Issue by robertofiguz** [CSDET10/GP2#12]
describe the activities of your use case for Add a Performance
(Remember to make appropriate checks)

**Comment by iTiagoL** [comment]
[GP2 Use Case DescriptionTemplate.docx](https://github.com/CSDET10/GP2/files/3945810/GP2.Use.Case.DescriptionTemplate.docx)

**Comment by robertofiguz** [comment]
[UC1-ADD PERFOMANCE TO THE LINEUP.docx](https://github.com/CSDET10/GP2/files/3955572/UC1-ADD.PERFOMANCE.TO.THE.LINEUP.docx)
