### ISSUE TITLE
Level 2 Data Flow diagram

### ISSUE THREAD

**Issue by robertofiguz** [CSDET10/GP2#14]
Level 2 Data Flow Diagram of processes which are likely to take place at the Security Office (ONLY).

These processes should:

- be consistent with Use Cases with the Security Office as an actor in your diagram for Part A

- have the Security Office as the location

- show data flows from/to external sources/sinks 

- show data flows from/to data stores within the system - these are likely to be Database tables but, at 

- this stage, they do not need to be fully normalised

**Comment by jcohen96** [comment]
![IMG_20191213_123600](https://user-images.githubusercontent.com/58332927/70800914-5fa9e300-1da5-11ea-9b71-05e05efaa283.jpg)

**Comment by robertofiguz** [comment]
@jcohen96  @mgrosmaninho @Matthew-Chamberlain @iTiagoL 
Hey! please confirm everything in the Level 2 flow diagram is correct and consistent or if there is something missing. (if you find everything to be all good react with a 👍 else just comment it please  )
[Level 2 Diagram](https://github.com/CSDET10/GP2/blob/master/Level%202%20diagram/level2_diagram.jpg)

**Comment by robertofiguz** [comment]
please compare with the requirements in this issue (#14) description

**Comment by mgrosmaninho** [comment]
> @jcohen96 @mgrosmaninho @Matthew-Chamberlain @iTiagoL
> Hey! please confirm everything in the Level 2 flow diagram is correct and consistent or if there is something missing. (if you find everything to be all good react with a 👍 else just comment it please )
> [Level 2 Diagram](https://github.com/CSDET10/GP2/blob/master/Level%202%20diagram/level2_diagram.jpg)

Looks fine for me.

**Comment by jcohen96** [comment]
I think is fine

**Comment by Matthew-Chamberlain** [comment]
i think it looks real good
